services:
  postgres:
    image: postgres:16
    container_name: med-module-postgres
    environment:
      POSTGRES_DB: med_module
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - med-module-postgres-data:/var/lib/postgresql/data

volumes:
  med-module-postgres-data:
